### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by AlexanderBykin** [liip/viewmodel-savedstate-helpers#7]
Hi.
I need your suggestions.
In my project i have `DataModel` that have `LiveData` fields.
That `DataModel` then used in `ViewModel` to bind to UI elements.
This approach allows me to transfer data models between screens.
How can I save this approach and use it with `SavedStateHandle`?
I also think `SavedStateHandleDelegate` should have method with immutable livedata initializer that have parameter to define value.

**Comment by AlexanderBykin** [comment]
An example how i'm doing that now
```
data class SomeModel(
    val firstName: ObservableField<String> = ObservableField(""),
    val lastName: ObservableField<String> = ObservableField(""),
    val middleName: ObservableField<String> = ObservableField("")
)

class SomeViewModel(app: Application) : AndroidViewModel(app) {
    val someModel = SomeModel() // this then binds to UI elements
}
```

**Comment by jschmid** [comment]
I am not sure to understand all of it.

First: is it related to this library? (_viewmodel-savedstate-helpers_) Otherwise you might want to post on Stackoverflow.

The "save state" library is to be used to save the state of a view when is it recreated (screen rotation, etc...). 

You should check those links if you want to share data between views:

* https://developer.android.com/topic/libraries/architecture/viewmodel#sharing
* https://developer.android.com/topic/libraries/architecture/saving-states
* https://developer.android.com/topic/libraries/architecture/viewmodel-savedstate

**Comment by jschmid** [comment]
Please re-open if you still have an issue.
